### ISSUE TITLE
Do you try install cppcheck with conan/conan-cmake and use?

### ISSUE THREAD

**Issue by eot42** [madduci/moderncpp-project-template#2]
I install gtest, cppcheck with conan-cmake but can not find cppcheck.

**Comment by madduci** [comment]
Hi 

thanks for your patient, I have just seen now the opened issue. What kind of error are you experiencing? How is named the `cppcheck` executable on your machine? Is it available on PATH?

Please check out [this file at line 6](https://github.com/madduci/moderncpp-project-template/blob/master/cmake/cppcheck.cmake#L6) and try to put the full path.

**Comment by eot42** [comment]
Sorry, it is not issue.
I try make my skeleton template based on [conan-cmake ](https://github.com/conan-io/cmake-conan) and I couldn't add cppcheck with conan-cmake.
