### ISSUE TITLE
Linking GLFW

### ISSUE THREAD

**Issue by icommit** [madduci/moderncpp-project-template#3]
I'm kinda confused on how to link/add glfw to the project. After successfully building conan with the glfw package included, I get the following errors when trying to run the example provided on the glfw website:

undefined reference to `glfwInit'

undefined reference to `glfwCreateWindow'

undefined reference to `glfwTerminate'

undefined reference to `glfwMakeContextCurren

**Comment by madduci** [comment]
Hi,

Thank you for using this project.
Woul you mind to share your CMakeLists.txt file?

I believe you haven't added the GLFW library in CMake, so it can be
recognised and used.
You need to add the "find" function, added the includes and link the
library to the executable.

Hope it helps


Il ven 13 ago 2021, 09:57 Omaru Bah ***@***.***> ha scritto:
